<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-StreamReader-81aee6ef-a7cc-4730-b67e-02c513015679</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.16.0" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.12.2" />
    <PackageReference Include="Azure.Messaging.EventHubs.Processor" Version="5.12.2" />
    <PackageReference Include="Azure.Storage.Files.DataLake" Version="12.23.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
    <PackageReference Include="System.Reactive" Version="6.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\projects\Storage\Storage.csproj" />
    <ProjectReference Include="..\..\projects\Models\Models.csproj" />
  </ItemGroup>
</Project>
